//! Emit `_features.h` and `_features.c` from `overlay/features.toml`.
//!
//! `_features.h` declares the symbols (custom keycode enum,
//! `process_record_user_overlay` weak forward decl) that both
//! `keymap.c` and `_features.c` reference. `_features.c` defines them.
//!
//! Concerns covered (Tier 1 declarative features):
//!
//! - `enum custom_keycodes` declaration (header) + dispatch (source)
//! - `key_override_t` table from `[[key_overrides]]`
//! - `combos[]` array from `[[combos]]`
//! - `process_record_user` dispatch — handles macros, then chains to
//!   `process_record_user_overlay` if a Tier 2 file declares one
//! - `get_tapping_term` overrides from `[[tapping_term_per_key]]`
//! - Achordion glue (callbacks + per-key overrides) from `[achordion]`
//!
//! The generated `process_record_user` is the authority — Tier 2 hooks
//! call into `process_record_user_overlay` after we've handled our own
//! concerns. (See the `process-record-user-collision` lint rule.)

use std::fmt::Write;

use anyhow::{anyhow, Context, Result};

use crate::schema::canonical::CanonicalLayout;
use crate::schema::features::{ChordStrategy, FeaturesToml};
use crate::schema::keycode::Keycode;
use crate::schema::layout::parse_action;

use super::keymap::emit_action;
use super::{CustomKeycodeTable, LayerTable, RgbKeycodeTable, TapDanceTable};

/// Default achordion timeout in milliseconds when no per-key override
/// is set. Matches the upstream achordion library default.
const ACHORDION_DEFAULT_TIMEOUT_MS: u32 = 800;

/// Translate a features.toml binding string (e.g. `"LT(Sym+Num, BSPC)"`)
/// into a valid C QMK token (e.g. `"LT(SYM_NUM, KC_BSPC)"`) by parsing
/// it through `schema::layout::parse_action` and re-emitting through
/// `keymap::emit_action`. Used by achordion + tapping_term emitters so
/// the user can write symbolic layer + bare keycode names.
///
/// Returns an error if the binding references a layer that doesn't
/// exist in the visual layout — the caller wraps the error with the
/// original binding string so the user can find the offending entry.
fn translate_binding(s: &str, layers: &LayerTable) -> Result<String> {
    let action = parse_action(s);
    emit_action(&action, layers, &CustomKeycodeTable::new())
        .with_context(|| format!("translating features.toml binding '{s}'"))
}

/// Emit `_features.h` — declarations both `keymap.c` and `_features.c`
/// reference, including the custom-keycode enum so the two translation
/// units agree on symbol IDs.
pub fn emit_features_h(
    custom_keycodes: &CustomKeycodeTable,
    rgb_keycodes: &RgbKeycodeTable,
    tap_dances: &TapDanceTable,
    layers: &LayerTable,
) -> String {
    let mut out = String::new();
    out.push_str("// SPDX-License-Identifier: MIT\n");
    out.push_str("// Generated by oryx-bench. Do not edit by hand.\n");
    out.push_str("#pragma once\n");
    out.push_str("#include QMK_KEYBOARD_H\n\n");

    // Layer enum -- shared between keymap.c and _features.c so both
    // translation units can reference layer names (e.g. in LT(), TO(),
    // achordion_timeout, combo layer filters).
    if !layers.is_empty() {
        out.push_str("enum layers {\n");
        let mut sorted: Vec<_> = layers.iter().collect();
        sorted.sort_by_key(|(_, v)| v.position);
        for (_, entry) in &sorted {
            let _ = writeln!(out, "    {},", entry.ident);
        }
        out.push_str("};\n\n");
    }

    if !custom_keycodes.is_empty() || !rgb_keycodes.is_empty() {
        out.push_str("enum custom_keycodes {\n");
        let mut first = true;
        let mut push_ident = |out: &mut String, ident: &str| {
            if first {
                let _ = writeln!(out, "    {ident} = SAFE_RANGE,");
                first = false;
            } else {
                let _ = writeln!(out, "    {ident},");
            }
        };
        for entry in custom_keycodes.values() {
            push_ident(&mut out, &entry.ident);
        }
        // Oryx-generated RGB keycodes (color swatches + RGB_SLD) —
        // same idents `emit_action` writes into keymap.c.
        if rgb_keycodes.uses_rgb_sld {
            push_ident(&mut out, "RGB_SLD");
        }
        for (h, s, v) in &rgb_keycodes.colors {
            push_ident(&mut out, &format!("HSV_{h}_{s}_{v}"));
        }
        out.push_str("};\n\n");
    }

    if !tap_dances.is_empty() {
        out.push_str("// Tap dance indices\n");
        out.push_str("enum tap_dance_ids {\n");
        for td in tap_dances {
            let _ = writeln!(out, "    TD_{},", td.td_index);
        }
        out.push_str("};\n\n");
        out.push_str("extern tap_dance_action_t tap_dance_actions[];\n\n");
    }

    out.push_str(
        "// Tier 2 (.zig/.c) overlay code may implement this hook to extend\n\
         // the generated process_record_user dispatch. Default is a no-op.\n",
    );
    out.push_str("bool process_record_user_overlay(uint16_t keycode, keyrecord_t *record);\n");
    out
}

/// Emit the full `_features.c` body.
///
/// Returns an error when codegen would silently produce broken C —
/// e.g. a combo binding that references an unknown position.
pub fn emit_features_c(
    features: &FeaturesToml,
    layers: &LayerTable,
    custom_keycodes: &CustomKeycodeTable,
    rgb_keycodes: &RgbKeycodeTable,
    _layout: &CanonicalLayout,
    tap_dances: &TapDanceTable,
) -> Result<String> {
    let mut out = String::new();
    out.push_str("// SPDX-License-Identifier: MIT\n");
    out.push_str("// Generated by oryx-bench. Do not edit by hand.\n");
    out.push_str("#include QMK_KEYBOARD_H\n");
    out.push_str("#include \"_features.h\"\n");
    if features
        .achordion
        .as_ref()
        .map(|a| a.enabled)
        .unwrap_or(false)
    {
        // Suppress deprecation #warning in legacy achordion.h — QMK
        // compiles with -Werror. Module-based replacement not in ZSA fork yet.
        out.push_str("#pragma GCC diagnostic push\n");
        out.push_str("#pragma GCC diagnostic ignored \"-Wcpp\"\n");
        out.push_str("#include \"achordion.h\"\n");
        out.push_str("#pragma GCC diagnostic pop\n");
    }
    out.push('\n');

    if !tap_dances.is_empty() {
        out.push_str(&emit_tap_dance_actions(
            tap_dances,
            layers,
            custom_keycodes,
        )?);
        out.push('\n');
    }

    if !features.key_overrides.is_empty() {
        out.push_str(&emit_key_overrides(features)?);
        out.push('\n');
    }

    if !features.tapping_term_per_key.is_empty() {
        out.push_str(&emit_tapping_term_per_key(features, layers)?);
        out.push('\n');
    }

    // NOTE: combos are emitted in keymap.c (not here) because QMK's
    // keymap_introspection.c includes keymap.c via `#include KEYMAP_C`
    // and expects `combo_t key_combos[]` to be visible there.

    if let Some(achordion) = &features.achordion {
        if achordion.enabled {
            out.push_str(&emit_achordion(features, layers)?);
            out.push('\n');
        }
    }

    out.push_str(&emit_process_record_user(
        custom_keycodes,
        rgb_keycodes,
        features,
    ));
    out.push('\n');

    Ok(out)
}

fn emit_key_overrides(features: &FeaturesToml) -> Result<String> {
    let mut out = String::from("// Key overrides\n");
    for (i, ko) in features.key_overrides.iter().enumerate() {
        let _ = writeln!(
            out,
            "static const key_override_t ko_{i} = ko_make_basic({}, {}, {});",
            mods_to_qmk(&ko.mods)?,
            normalize_keycode_token(&ko.key),
            normalize_keycode_token(&ko.sends)
        );
    }
    out.push_str("const key_override_t **key_overrides = (const key_override_t *[]){\n");
    for (i, _) in features.key_overrides.iter().enumerate() {
        let _ = writeln!(out, "    &ko_{i},");
    }
    out.push_str("    NULL\n};\n");
    Ok(out)
}

fn mods_to_qmk(mods: &[String]) -> Result<String> {
    if mods.is_empty() {
        return Ok("0".to_string());
    }
    let mut parts = Vec::with_capacity(mods.len());
    for raw in mods {
        let bare = raw.trim_start_matches("KC_").trim_start_matches("MOD_");
        if !is_valid_modifier_token(bare) {
            return Err(anyhow!(
                "key_override mods entry '{raw}' is not a recognized QMK modifier"
            ));
        }
        let canonical = normalize_mod_token(bare);
        parts.push(format!("MOD_{canonical}"));
    }
    Ok(parts.join(" | "))
}

/// Map user-friendly modifier aliases to QMK canonical short names.
fn normalize_mod_token(t: &str) -> &str {
    match t {
        "LSHIFT" => "LSFT",
        "RSHIFT" => "RSFT",
        "LCTRL" => "LCTL",
        "RCTRL" => "RCTL",
        other => other,
    }
}

fn is_valid_modifier_token(t: &str) -> bool {
    matches!(
        t,
        "LCTL"
            | "LSFT"
            | "LALT"
            | "LGUI"
            | "RCTL"
            | "RSFT"
            | "RALT"
            | "RGUI"
            | "LSHIFT"
            | "RSHIFT"
            | "LCTRL"
            | "RCTRL"
            | "HYPR"
            | "MEH"
    )
}

/// Normalize a keycode token written by the user in `features.toml`
/// into a QMK-compatible C token. Handles bare names (`BSPC` →
/// `KC_BSPC`), already-prefixed names (`KC_BSPC` → `KC_BSPC`), and
/// modifier wrappers like `S(GRAVE)` (recursing into the parens to
/// rewrite the inner token as `S(KC_GRAVE)`).
fn normalize_keycode_token(s: &str) -> String {
    let trimmed = s.trim();
    if let Some(open) = trimmed.find('(') {
        if let Some(close) = trimmed.rfind(')') {
            if close > open {
                let head = &trimmed[..open];
                let inner = &trimmed[open + 1..close];
                let rest = &trimmed[close + 1..];
                // Recursively normalize the inner token; supports
                // arbitrary nesting like `LCTL(LSFT(GRAVE))`.
                return format!("{head}({}){rest}", normalize_keycode_token(inner));
            }
        }
    }
    if trimmed.starts_with("KC_") || trimmed.starts_with("QK_") {
        return trimmed.to_string();
    }
    // Bare name. Reject if it's not actually a known QMK keycode after
    // adding the prefix — that catches typos like `BACKSPC` early.
    let candidate = format!("KC_{trimmed}");
    if matches!(Keycode::from_str(&candidate), Keycode::Other(_)) {
        // Still emit the prefixed form so QMK gets a recognizable
        // token; lint will catch unknown keycodes separately.
        return candidate;
    }
    candidate
}

fn emit_tapping_term_per_key(features: &FeaturesToml, layers: &LayerTable) -> Result<String> {
    let mut out =
        String::from("uint16_t get_tapping_term(uint16_t keycode, keyrecord_t *record) {\n");
    out.push_str("    switch (keycode) {\n");
    for entry in &features.tapping_term_per_key {
        let translated = translate_binding(&entry.binding, layers)?;
        let _ = writeln!(out, "        case {translated}: return {};", entry.ms);
    }
    out.push_str("        default: return TAPPING_TERM;\n");
    out.push_str("    }\n");
    out.push_str("}\n");
    Ok(out)
}

fn emit_process_record_user(
    custom_keycodes: &CustomKeycodeTable,
    rgb_keycodes: &RgbKeycodeTable,
    _features: &FeaturesToml,
) -> String {
    let mut out = String::new();
    out.push_str("// Forward declaration: Tier 2 (.zig/.c) overlay code may implement this.\n");
    out.push_str("__attribute__((weak)) bool process_record_user_overlay(uint16_t keycode, keyrecord_t *record) { return true; }\n\n");
    out.push_str("bool process_record_user(uint16_t keycode, keyrecord_t *record) {\n");
    out.push_str("    if (record->event.pressed) {\n");
    out.push_str("        switch (keycode) {\n");
    for entry in custom_keycodes.values() {
        let escaped = escape_c_string(&entry.body);
        let _ = writeln!(
            out,
            "            case {}: SEND_STRING(\"{escaped}\"); return false;",
            entry.ident
        );
    }
    // Oryx-generated RGB keycodes. `rgblight_*` is the spelling ZSA's
    // QMK fork uses in its own Oryx exports; on RGB-matrix boards
    // (Moonlander, Voyager) the fork's rgb_matrix.h #defines them to
    // the rgb_matrix_* equivalents.
    if rgb_keycodes.uses_rgb_sld {
        out.push_str("            case RGB_SLD: rgblight_mode(1); return false;\n");
    }
    for (h, s, v) in &rgb_keycodes.colors {
        let _ = writeln!(
            out,
            "            case HSV_{h}_{s}_{v}: rgblight_mode(1); rgblight_sethsv({h}, {s}, {v}); return false;"
        );
    }
    out.push_str("            default: break;\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("    return process_record_user_overlay(keycode, record);\n");
    out.push_str("}\n");
    out
}

/// Escape a Rust string for embedding inside a C `"..."` string literal.
///
/// Handles every byte that would otherwise terminate the literal,
/// change its semantics, or be non-representable:
///
/// - `\`, `"`: the two characters that would break the literal syntax.
/// - `\n`, `\r`, `\t`: common whitespace; emitted as escapes so the
///   generated file stays on a single line.
/// - `\0`: would truncate the literal at compile time — `char s[] =
///   "foo\0bar"` stores `"foo"`. Emitted as `\0` so QMK's SEND_STRING
///   receives the exact byte we mean. (In practice users shouldn't
///   put nulls in macros, but the rule is "any input is safe to
///   pass to this function".)
/// - Other ASCII control characters (`<0x20` or `0x7F`): emitted in
///   `\xNN""` form. The trailing empty string is **load-bearing**:
///   C's `\x` escape is greedy and consumes any subsequent hex digits
///   without bound, so `"\x07A"` would parse as one character with
///   value `0x7A` (silently dropping the BEL we meant to escape).
///   Adjacent string literals are concatenated at translation phase
///   6, so `"\x07" "A"` collapses back to a 2-char string `BEL` + `A`
///   while terminating the hex run. See ISO C99 6.4.4.4 ¶7.
/// - Non-ASCII UTF-8 passes through unchanged: the user's source
///   already decided how to encode it and the C compiler treats
///   high-bit bytes as part of the string.
fn escape_c_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\0' => out.push_str("\\0"),
            // Other ASCII control characters. The `""` after the hex
            // escape terminates C's greedy hex-digit run; see the
            // doc comment above for the rationale.
            c if (c as u32) < 0x20 || (c as u32) == 0x7F => {
                use std::fmt::Write as _;
                let _ = write!(out, "\\x{:02X}\"\"", c as u32);
            }
            c => out.push(c),
        }
    }
    out
}

// =============================================================================
// Combos
// =============================================================================

/// Emit `combo_t key_combos[]` from `[[combos]]`. Position names are
/// resolved to keycodes via the visual layout — each combo lists the
/// keycodes that must be pressed simultaneously.
///
/// Returns an error if any combo references an unknown layer, an
/// unknown position, an unknown geometry, or a position with an
/// unbound key. The previous behavior of writing a `// skipped`
/// comment into the C source silently dropped combos at build time;
/// failing the build is the only way to surface the bug.
pub fn emit_combos(features: &FeaturesToml, layout: &CanonicalLayout) -> Result<String> {
    let mut out = String::from("// Combos\n");

    let geom = crate::schema::geometry::get(layout.geometry.as_str()).ok_or_else(|| {
        anyhow!(
            "combos defined in features.toml but layout uses unknown geometry '{}'",
            layout.geometry
        )
    })?;

    for (i, combo) in features.combos.iter().enumerate() {
        // Resolve each position name to the keycode bound at that position
        // on the relevant layer (default: layer 0).
        let layer_name = combo.layer.as_deref().unwrap_or("Main");
        let layer = layout
            .layers
            .iter()
            .find(|l| l.name == layer_name)
            .or_else(|| layout.layers.iter().find(|l| l.position == 0))
            .ok_or_else(|| {
                anyhow!("combo #{i} references layer '{layer_name}' which does not exist")
            })?;
        let mut codes: Vec<String> = Vec::with_capacity(combo.keys.len());
        for pos in &combo.keys {
            let idx = geom.position_to_index(pos).ok_or_else(|| {
                anyhow!(
                    "combo #{i} references position '{pos}' which is not valid for geometry '{}'",
                    layout.geometry
                )
            })?;
            let key = &layer.keys[idx];
            let kc = key
                .tap
                .as_ref()
                .and_then(|a| a.tap_keycode())
                .ok_or_else(|| {
                    anyhow!(
                        "combo #{i} references position '{pos}' on layer '{layer_name}' which has no bound keycode (combos must reference real keycodes)"
                    )
                })?;
            codes.push(kc.canonical_name().into_owned());
        }
        let _ = writeln!(
            out,
            "static const uint16_t PROGMEM combo_{i}[] = {{ {}, COMBO_END }};",
            codes.join(", ")
        );
    }

    out.push_str("combo_t key_combos[] = {\n");
    for (i, combo) in features.combos.iter().enumerate() {
        let sends = normalize_keycode_token(&combo.sends);
        let _ = writeln!(out, "    [{i}] = COMBO(combo_{i}, {sends}),");
    }
    out.push_str("};\n");

    Ok(out)
}

// =============================================================================
// Achordion
// =============================================================================

/// Emit achordion glue: callbacks for chord_strategy, per-key timeouts,
/// and no_streak overrides. Achordion's library body itself is **vendored**
/// upstream — the user must drop `achordion.c` and `achordion.h` into
/// `overlay/`. We document this in the cookbook.
fn emit_achordion(features: &FeaturesToml, layers: &LayerTable) -> Result<String> {
    let achordion = match &features.achordion {
        Some(a) if a.enabled => a,
        _ => return Ok(String::new()),
    };

    let mut out = String::from("// Achordion glue\n");
    out.push_str("// NOTE: requires `achordion.h` + `achordion.c` from\n");
    out.push_str("// https://getreuer.info/posts/keyboards/achordion/ to be vendored\n");
    out.push_str("// in overlay/.\n\n");

    // achordion_chord — implements chord_strategy.
    out.push_str("bool achordion_chord(uint16_t tap_hold_keycode, keyrecord_t* tap_hold_record,\n");
    out.push_str("                     uint16_t other_keycode, keyrecord_t* other_record) {\n");

    // Emit same_hand_allow exceptions first.
    for entry in &achordion.same_hand_allow {
        let tap_hold = translate_binding(&entry.tap_hold, layers)?;
        let other = translate_binding(&entry.other, layers)?;
        let _ = writeln!(
            out,
            "    if (tap_hold_keycode == {tap_hold} && other_keycode == {other}) return true;"
        );
    }

    match achordion.chord_strategy {
        ChordStrategy::Always => out.push_str("    return true;\n"),
        ChordStrategy::Never => out.push_str("    return false;\n"),
        ChordStrategy::OppositeHands => {
            out.push_str("    return achordion_opposite_hands(tap_hold_record, other_record);\n");
        }
    }
    out.push_str("}\n\n");

    // achordion_timeout — per-key timeout overrides.
    if !achordion.timeout.is_empty() {
        out.push_str("uint16_t achordion_timeout(uint16_t tap_hold_keycode) {\n");
        out.push_str("    switch (tap_hold_keycode) {\n");
        for entry in &achordion.timeout {
            let translated = translate_binding(&entry.binding, layers)?;
            let _ = writeln!(out, "        case {translated}: return {};", entry.ms);
        }
        let _ = writeln!(
            out,
            "        default: return {ACHORDION_DEFAULT_TIMEOUT_MS};"
        );
        out.push_str("    }\n");
        out.push_str("}\n\n");
    }

    // achordion_streak_chord — disable streak chord disambiguation per-key.
    if !achordion.no_streak.is_empty() {
        out.push_str("bool achordion_streak_chord(uint16_t tap_hold_keycode) {\n");
        out.push_str("    switch (tap_hold_keycode) {\n");
        for entry in &achordion.no_streak {
            let translated = translate_binding(&entry.binding, layers)?;
            let _ = writeln!(out, "        case {translated}: return false;");
        }
        out.push_str("        default: return true;\n");
        out.push_str("    }\n");
        out.push_str("}\n");
    }

    Ok(out)
}

// =============================================================================
// Tap dance
// =============================================================================

/// Emit `tap_dance_action_t tap_dance_actions[]` from keys that use
/// `double_tap`. Each entry maps to an `ACTION_TAP_DANCE_DOUBLE(single, double)`.
fn emit_tap_dance_actions(
    tap_dances: &TapDanceTable,
    layers: &LayerTable,
    custom_keycodes: &CustomKeycodeTable,
) -> Result<String> {
    let mut out = String::from("// Tap dance actions\n");
    out.push_str("tap_dance_action_t tap_dance_actions[] = {\n");
    for td in tap_dances {
        let single = match &td.single_tap {
            Some(a) => emit_action(a, layers, custom_keycodes)?,
            None => "KC_NO".to_string(),
        };
        let double = emit_action(&td.double_tap, layers, custom_keycodes)?;
        let _ = writeln!(
            out,
            "    [TD_{}] = ACTION_TAP_DANCE_DOUBLE({}, {}),",
            td.td_index, single, double
        );
    }
    out.push_str("};\n");
    Ok(out)
}
#[cfg(test)]
mod tests {
    use super::*;
    use crate::generate::TapDanceTable;
    use crate::schema::features::{FeaturesToml, KeyOverride, MacroDef};

    #[test]
    fn escape_c_string_handles_backslash_and_quote() {
        assert_eq!(escape_c_string(r#"say "hi""#), r#"say \"hi\""#);
        assert_eq!(escape_c_string(r"path\to\file"), r"path\\to\\file");
    }

    #[test]
    fn escape_c_string_handles_whitespace() {
        assert_eq!(escape_c_string("a\nb\tc\rd"), "a\\nb\\tc\\rd");
    }

    #[test]
    fn escape_c_string_handles_null_byte() {
        // Critical: a raw \0 in a C literal truncates the string.
        // The generator must emit \0 explicitly.
        assert_eq!(escape_c_string("foo\0bar"), "foo\\0bar");
    }

    #[test]
    fn escape_c_string_handles_control_chars() {
        // BELL (0x07) and DEL (0x7F) round-trip as hex escapes
        // terminated by `""` so a following hex-digit character
        // doesn't get absorbed into the escape.
        assert_eq!(escape_c_string("\x07"), "\\x07\"\"");
        assert_eq!(escape_c_string("\x7F"), "\\x7F\"\"");
    }

    #[test]
    fn escape_c_string_control_char_followed_by_hex_digit_letter() {
        // Regression for the `\xNN` greediness bug: a control char
        // followed by an ASCII letter that happens to be a hex digit
        // (`A`..`F` or `a`..`f`) would otherwise be silently merged
        // into a single hex escape by the C compiler. The trailing
        // `""` empty string terminates the hex run; the next literal
        // character then appears as itself.
        let escaped = escape_c_string("\x07A");
        assert_eq!(
            escaped, "\\x07\"\"A",
            "expected hex escape terminated by empty string before A"
        );

        // And the corresponding lowercase case.
        let escaped_lower = escape_c_string("\x07b");
        assert_eq!(escaped_lower, "\\x07\"\"b");

        // A control char followed by a non-hex letter is also fine
        // — the bug only triggers with hex letters, but the escape
        // shape is uniform, so this is regression-tested too.
        let escaped_g = escape_c_string("\x07G");
        assert_eq!(escaped_g, "\\x07\"\"G");
    }

    #[test]
    fn escape_c_string_passes_through_utf8() {
        // High-bit bytes are left alone — the generator never tries
        // to transcode user input.
        assert_eq!(escape_c_string("café"), "café");
    }

    #[test]
    fn emit_key_overrides_table() {
        let features = FeaturesToml {
            key_overrides: vec![KeyOverride {
                mods: vec!["LSHIFT".into()],
                key: "BSPC".into(),
                sends: "DELETE".into(),
                layers: None,
            }],
            ..Default::default()
        };
        let out = emit_key_overrides(&features).unwrap();
        assert!(out.contains("MOD_LSFT"));
        assert!(out.contains("KC_BSPC"));
        assert!(out.contains("KC_DELETE"));
        assert!(out.contains("ko_make_basic"));
    }

    #[test]
    fn emit_key_overrides_recurses_into_paren_wrappers() {
        // Regression for the `S(GRAVE)` bug where the old
        // `with_kc_prefix` left the inner token unprefixed and emitted
        // broken C. Verifies the new `normalize_keycode_token` recurses.
        let features = FeaturesToml {
            key_overrides: vec![KeyOverride {
                mods: vec!["LSHIFT".into()],
                key: "ESC".into(),
                sends: "S(GRAVE)".into(),
                layers: None,
            }],
            ..Default::default()
        };
        let out = emit_key_overrides(&features).unwrap();
        assert!(out.contains("S(KC_GRAVE)"), "got: {out}");
        assert!(!out.contains("S(GRAVE)"), "unprefixed inner token: {out}");
    }

    #[test]
    fn emit_key_overrides_rejects_invalid_modifier() {
        let features = FeaturesToml {
            key_overrides: vec![KeyOverride {
                mods: vec!["LSHF".into()], // typo
                key: "BSPC".into(),
                sends: "DELETE".into(),
                layers: None,
            }],
            ..Default::default()
        };
        let err = emit_key_overrides(&features).unwrap_err();
        assert!(err.to_string().contains("LSHF"));
    }

    #[test]
    fn emit_macro_dispatch() {
        let mut custom = CustomKeycodeTable::new();
        custom.insert(
            "USER01".into(),
            super::super::CustomKeycodeEntry {
                ident: "CK_EMAIL".into(),
                body: "you@example.com".into(),
            },
        );
        let features = FeaturesToml::default();
        let out = emit_process_record_user(&custom, &RgbKeycodeTable::default(), &features);
        assert!(out.contains("CK_EMAIL"));
        assert!(out.contains("SEND_STRING"));
        assert!(out.contains("you@example.com"));
        assert!(out.contains("process_record_user_overlay"));
    }

    #[test]
    fn macro_with_newline_is_escaped() {
        let mut custom = CustomKeycodeTable::new();
        custom.insert(
            "USER02".into(),
            super::super::CustomKeycodeEntry {
                ident: "CK_GIT".into(),
                body: "git status\n".into(),
            },
        );
        let out = emit_process_record_user(
            &custom,
            &RgbKeycodeTable::default(),
            &FeaturesToml::default(),
        );
        assert!(out.contains("git status\\n"));
    }

    #[test]
    fn emit_features_c_with_no_features_still_produces_dispatch() {
        let features = FeaturesToml::default();
        let custom = CustomKeycodeTable::new();
        let layers = LayerTable::new();
        let layout = CanonicalLayout {
            geometry: "voyager".into(),
            title: "test".into(),
            layers: vec![],
            combos: Vec::new(),
            config: Default::default(),
        };
        let out = emit_features_c(
            &features,
            &layers,
            &custom,
            &RgbKeycodeTable::default(),
            &layout,
            &TapDanceTable::new(),
        )
        .unwrap();
        assert!(out.contains("process_record_user"));
        assert!(out.contains("process_record_user_overlay"));
    }

    #[test]
    fn emit_features_h_includes_custom_keycode_enum() {
        let mut custom = CustomKeycodeTable::new();
        custom.insert(
            "USER01".into(),
            super::super::CustomKeycodeEntry {
                ident: "CK_EMAIL".into(),
                body: "you@example.com".into(),
            },
        );
        let h = emit_features_h(
            &custom,
            &RgbKeycodeTable::default(),
            &TapDanceTable::new(),
            &LayerTable::new(),
        );
        assert!(h.contains("#pragma once"));
        assert!(h.contains("enum custom_keycodes"));
        assert!(h.contains("CK_EMAIL = SAFE_RANGE"));
        assert!(h.contains("process_record_user_overlay"));
    }

    #[test]
    fn emit_features_h_omits_enum_when_no_macros() {
        let custom = CustomKeycodeTable::new();
        let h = emit_features_h(
            &custom,
            &RgbKeycodeTable::default(),
            &TapDanceTable::new(),
            &LayerTable::new(),
        );
        assert!(h.contains("#pragma once"));
        assert!(!h.contains("enum custom_keycodes"));
        // The forward decl is unconditional so Tier 2 hooks always link.
        assert!(h.contains("process_record_user_overlay"));
    }

    #[test]
    fn emit_combos_resolves_position_names_to_keycodes() {
        use crate::schema::canonical::{CanonicalAction, CanonicalKey, CanonicalLayer};
        use crate::schema::features::Combo;
        use crate::schema::keycode::Keycode;

        let mut keys = vec![CanonicalKey::default(); 52];
        // L_index_top is index 10, L_middle_top is index 9 in the
        // new column-first naming.
        keys[10] = CanonicalKey {
            tap: Some(CanonicalAction::Keycode(Keycode::KcF)),
            ..Default::default()
        };
        keys[9] = CanonicalKey {
            tap: Some(CanonicalAction::Keycode(Keycode::KcD)),
            ..Default::default()
        };
        let layout = CanonicalLayout {
            geometry: "voyager".into(),
            title: "test".into(),
            layers: vec![CanonicalLayer {
                name: "Main".into(),
                position: 0,
                keys,
            }],
            combos: Vec::new(),
            config: Default::default(),
        };
        let features = FeaturesToml {
            combos: vec![Combo {
                keys: vec!["L_index_top".into(), "L_middle_top".into()],
                sends: "ESC".into(),
                layer: Some("Main".into()),
                timeout_ms: None,
            }],
            ..Default::default()
        };
        let out = emit_combos(&features, &layout).unwrap();
        assert!(out.contains("KC_F"));
        assert!(out.contains("KC_D"));
        assert!(out.contains("COMBO_END"));
        assert!(out.contains("COMBO(combo_0, KC_ESC)"));
    }

    #[test]
    fn emit_combos_errors_on_unknown_position() {
        use crate::schema::canonical::{CanonicalKey, CanonicalLayer};
        use crate::schema::features::Combo;

        let layout = CanonicalLayout {
            geometry: "voyager".into(),
            title: "test".into(),
            layers: vec![CanonicalLayer {
                name: "Main".into(),
                position: 0,
                keys: vec![CanonicalKey::default(); 52],
            }],
            combos: Vec::new(),
            config: Default::default(),
        };
        let features = FeaturesToml {
            combos: vec![Combo {
                keys: vec!["L_ghost_top".into()],
                sends: "ESC".into(),
                layer: Some("Main".into()),
                timeout_ms: None,
            }],
            ..Default::default()
        };
        let err = emit_combos(&features, &layout).unwrap_err();
        assert!(err.to_string().contains("L_ghost_top"));
    }

    #[test]
    fn normalize_keycode_token_handles_paren_wrappers() {
        // The fixture's `S(GRAVE)` key override must emit `S(KC_GRAVE)`,
        // not the broken `S(GRAVE)` that the old `with_kc_prefix` did.
        assert_eq!(normalize_keycode_token("BSPC"), "KC_BSPC");
        assert_eq!(normalize_keycode_token("KC_BSPC"), "KC_BSPC");
        assert_eq!(normalize_keycode_token("S(GRAVE)"), "S(KC_GRAVE)");
        assert_eq!(normalize_keycode_token("S(KC_GRAVE)"), "S(KC_GRAVE)");
        // Nested wrappers also recurse.
        assert_eq!(
            normalize_keycode_token("LCTL(LSFT(GRAVE))"),
            "LCTL(LSFT(KC_GRAVE))"
        );
    }

    #[test]
    fn emit_achordion_with_opposite_hands_strategy() {
        use crate::generate::LayerEntry;
        use crate::schema::features::{Achordion, AchordionBinding, AchordionTimeout};
        let features = FeaturesToml {
            achordion: Some(Achordion {
                enabled: true,
                chord_strategy: ChordStrategy::OppositeHands,
                timeout: vec![AchordionTimeout {
                    binding: "LT(SYM_NUM, KC_BSPC)".into(),
                    ms: 600,
                }],
                no_streak: vec![AchordionBinding {
                    binding: "LT(SYM_NUM, KC_BSPC)".into(),
                }],
                same_hand_allow: vec![],
            }),
            ..Default::default()
        };
        // Populate the layer table so the binding translation can
        // resolve `SYM_NUM` — emit_action now errors on unknown layer
        // refs instead of silently passing the name through.
        let mut layers = LayerTable::new();
        layers.insert(
            "SYM_NUM".to_string(),
            LayerEntry {
                ident: "SYM_NUM".to_string(),
                position: 1,
            },
        );
        let out = emit_achordion(&features, &layers).unwrap();
        assert!(out.contains("achordion_chord"));
        assert!(out.contains("achordion_opposite_hands"));
        assert!(out.contains("achordion_timeout"));
        assert!(out.contains("LT(SYM_NUM, KC_BSPC): return 600"));
        assert!(out.contains("achordion_streak_chord"));
    }

    #[test]
    fn unused_macro_def_field() {
        // Touch the MacroDef type so the import is exercised.
        let _ = MacroDef {
            name: "X".into(),
            sends: "y".into(),
            slot: None,
        };
    }

    #[test]
    fn emit_tap_dance_actions_array() {
        use crate::generate::TapDanceEntry;
        use crate::schema::canonical::{CanonicalAction, LayerRef};

        let mut layers = LayerTable::new();
        layers.insert(
            "Gaming".into(),
            super::super::LayerEntry {
                ident: "GAMING".into(),
                position: 1,
            },
        );
        let tap_dances = vec![TapDanceEntry {
            td_index: 0,
            layer_position: 0,
            key_index: 10,
            single_tap: None,
            double_tap: CanonicalAction::To {
                layer: LayerRef::Name("Gaming".into()),
            },
        }];
        let out = emit_tap_dance_actions(&tap_dances, &layers, &CustomKeycodeTable::new()).unwrap();
        assert!(out.contains("tap_dance_action_t tap_dance_actions[]"));
        assert!(out.contains("ACTION_TAP_DANCE_DOUBLE(KC_NO, TO(GAMING))"));
    }

    #[test]
    fn emit_features_h_includes_td_enum_when_tap_dances_exist() {
        use crate::generate::TapDanceEntry;
        use crate::schema::canonical::{CanonicalAction, LayerRef};

        let tap_dances = vec![TapDanceEntry {
            td_index: 0,
            layer_position: 0,
            key_index: 10,
            single_tap: None,
            double_tap: CanonicalAction::To {
                layer: LayerRef::Name("Gaming".into()),
            },
        }];
        let h = emit_features_h(
            &CustomKeycodeTable::new(),
            &RgbKeycodeTable::default(),
            &tap_dances,
            &LayerTable::new(),
        );
        assert!(h.contains("enum tap_dance_ids"));
        assert!(h.contains("TD_0"));
        assert!(h.contains("extern tap_dance_action_t tap_dance_actions[]"));
    }

    #[test]
    fn emit_features_h_omits_td_enum_when_no_tap_dances() {
        let h = emit_features_h(
            &CustomKeycodeTable::new(),
            &RgbKeycodeTable::default(),
            &TapDanceTable::new(),
            &LayerTable::new(),
        );
        assert!(!h.contains("tap_dance_ids"));
        assert!(!h.contains("tap_dance_actions"));
    }

    #[test]
    fn rgb_keycodes_emit_enum_and_handlers() {
        let rgb = RgbKeycodeTable {
            colors: vec![(0, 255, 255), (74, 255, 206)],
            uses_rgb_sld: true,
        };
        let h = emit_features_h(
            &CustomKeycodeTable::new(),
            &rgb,
            &TapDanceTable::new(),
            &LayerTable::new(),
        );
        // With no macros, the first RGB entry anchors SAFE_RANGE.
        assert!(h.contains("enum custom_keycodes"));
        assert!(h.contains("RGB_SLD = SAFE_RANGE,"));
        assert!(h.contains("HSV_0_255_255,"));
        assert!(h.contains("HSV_74_255_206,"));

        let out =
            emit_process_record_user(&CustomKeycodeTable::new(), &rgb, &FeaturesToml::default());
        assert!(out.contains("case RGB_SLD: rgblight_mode(1); return false;"));
        assert!(out.contains(
            "case HSV_74_255_206: rgblight_mode(1); rgblight_sethsv(74, 255, 206); return false;"
        ));
    }

    #[test]
    fn macros_anchor_safe_range_before_rgb_keycodes() {
        let mut custom = CustomKeycodeTable::new();
        custom.insert(
            "USER01".into(),
            super::super::CustomKeycodeEntry {
                ident: "CK_EMAIL".into(),
                body: "you@example.com".into(),
            },
        );
        let rgb = RgbKeycodeTable {
            colors: vec![(0, 255, 255)],
            uses_rgb_sld: false,
        };
        let h = emit_features_h(&custom, &rgb, &TapDanceTable::new(), &LayerTable::new());
        assert!(h.contains("CK_EMAIL = SAFE_RANGE,"));
        // RGB entries follow without a second SAFE_RANGE anchor.
        assert!(h.contains("HSV_0_255_255,"));
        assert_eq!(h.matches("SAFE_RANGE").count(), 1);
    }
}
